##################################################
### Install required packages
- name: Install required packages
  apt: name={{ item }} state=present
  with_items:
    - curl
    - openssh-server
    - ca-certificates

##################################################
### Install Gitlab
- name: Download Installer
  get_url:
    url="https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh"
    dest="/tmp/gitlab_installer.sh"
    mode=777
    force=yes

- name: Run Installer
  shell: /tmp/gitlab_installer.sh
  args:
    executable: /bin/bash

- name: Install Gitlab
  apt: name={{ item }} state=latest
  with_items:
    - gitlab-ce
  environment: 
    EXTERNAL_URL: http://gitlab.test

##################################################
### Configure firewall
- name: Allow port 80 for Gitlab
  ufw: rule=allow port=80