##################################################
### Install required packages
- name: Install required packages
  apt: name={{ item }} state=present
  with_items:
    - curl
    - openssh-server
    - ca-certificates

##################################################
### Install Gitlab
- name: Download Gitlab Installer
  get_url:
    url="https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh"
    dest="/tmp/gitlab_installer.sh"
    mode=777

- name: Run Gitlab Installer
  command: /tmp/gitlab_installer.sh

- name: Install Gitlab
  apt: name={{ item }} state=latest
  with_items:
    - gitlab-ce
  environment: 
    EXTERNAL_URL: http://gitlab.test

##################################################
### Install Gitlab-Runner
- name: Download Gitlab-Runner Installer
  get_url:
    url="https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh"
    dest="/tmp/gitlab_runner_installer.sh"
    mode=777

- name: Run Gitlab-Runner Installer
  command: /tmp/gitlab_runner_installer.sh

- name: Install Gitlab-Runner
  apt: name={{ item }} state=latest
  with_items:
    - gitlab-runner

##################################################
### Configure firewall
- name: Allow port 80 for Gitlab
  ufw: rule=allow port=80